### ISSUE TITLE
Help Building

### ISSUE THREAD

**Issue by mister-monkey789** [JoshuaMKW/JuniorsToolbox#17]
I want to try this tool, but I am having trouble building it. I have spent the better part of two days trying to build it without asking for help, but no matter what I tried, I could not get CMake to work right. If possible, I think instructions for this would be great to have in the readme file. 

I appreciate any help that you can provide! 

_(I've never posted an issue on GitHub before, so I hope I did this right)_

**Comment by JoshuaMKW** [comment]
Instructions would be helpful for sure! I plan on adding instructions and guidance once the project is further in development.

That being said, could you provide your CMake build errors? I really can't do anything to help you without proper context.

**Comment by mister-monkey789** [comment]
Here are the errors I get:
```
CMake Error at C:/Program Files/CMake/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Iconv (missing: Iconv_LIBRARY Iconv_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.28/Modules/FindIconv.cmake:165 (find_package_handle_standard_args)
  CMakeLists.txt:77 (find_package)


Configuring incomplete, errors occurred!
```


I'm not sure if you need the context for these errors, but this is the full output when I use the CMake gui

```
Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22631.
The C compiler identification is MSVC 19.39.33519.0
The CXX compiler identification is MSVC 19.39.33519.0
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe - skipped
Detecting C compile features
Detecting C compile features - done
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe - skipped
Detecting CXX compile features
Detecting CXX compile features - done
GLM: Version 0.9.9.9
Performing Test CMAKE_HAVE_LIBC_PTHREAD
Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
Looking for pthread_create in pthreads
Looking for pthread_create in pthreads - not found
Looking for pthread_create in pthread
Looking for pthread_create in pthread - not found
Found Threads: TRUE  
Found Doxygen: C:/Program Files/doxygen/bin/doxygen.exe (found version "1.10.0") found components: doxygen 
Including Win32 support
CMake Error at C:/Program Files/CMake/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Iconv (missing: Iconv_LIBRARY Iconv_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.28/Modules/FindIconv.cmake:165 (find_package_handle_standard_args)
  CMakeLists.txt:77 (find_package)


Configuring incomplete, errors occurred!
```
I have tried editing the CMakeLists.txt to have

```set(CMAKE_PREFIX_PATH "C:/msys64/mingw64/")
# find_package(ICU 61.0 COMPONENTS uc i18n REQUIRED)
set(Iconv_LIBRARY "C:/msys64/mingw64/lib")
set(Iconv_INCLUDE "C:/msys64/mingw64/include")
find_package(Iconv REQUIRED)
```
so that CMake can find my Iconv, but this is what happens

```Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22631.
The C compiler identification is MSVC 19.39.33519.0
The CXX compiler identification is MSVC 19.39.33519.0
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe - skipped
Detecting C compile features
Detecting C compile features - done
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe - skipped
Detecting CXX compile features
Detecting CXX compile features - done
CMake Deprecation Warning at lib/J3DUltra/lib/glm/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at lib/J3DUltra/lib/glm/CMakeLists.txt:2 (cmake_policy):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


GLM: Version 0.9.9.9
Performing Test CMAKE_HAVE_LIBC_PTHREAD
Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
Looking for pthread_create in pthreads
Looking for pthread_create in pthreads - not found
Looking for pthread_create in pthread
Looking for pthread_create in pthread - not found
Found Threads: TRUE  
Found Doxygen: C:/Program Files/doxygen/bin/doxygen.exe (found version "1.10.0") found components: doxygen 
Including Win32 support
Found Iconv: C:/msys64/mingw64/lib (found version "1.17") 
Configuring done (4.3s)
```

**Comment by JoshuaMKW** [comment]
It seems like it found your Iconv installation after your edits? Am I missing something here?

As for getting the pre-modified cmake to work properly, you need to make sure you install Iconv and such using the vcpkg.json that is included with the project.

**Comment by JoshuaMKW** [comment]
Considering the inactivity, I'm closing this issue until further comment.

**Comment by mister-monkey789** [comment]
Sorry for the delay in my response. Finals didn't leave me much free time. 

I didn't notice the vcpkg.json before. Now that I used that, I still had to edit the CMakeLists.txt to tell it where the library files and include folder were, but I am able to compile and build it, but when I run the JuniorsToolbox.exe , I get this system error message: `The code execution cannot proceed because iconv-2.dll was not found. Reinstalling the program may fix this problem.`

I have tried building it and compiling it again, but it says the same thing. I'm not sure if it is relevant, but I am using Visual Studio Community 2022 version 17.9.0

**Comment by JoshuaMKW** [comment]
Seems like iconv isn't being copied into the build folder alongside JuniorsToolbox.exe

I can't really say why this is happening, obviously something in the build process is not functioning properly and in your case editing the CMakeLists likely was a fluke fix. I'd recommend reattempting the vcpkg install and instead determine why you have to edit the CMakeLists in the first place. Let me know how it goes.

**Comment by mister-monkey789** [comment]
I realized that I have been doing things manually that are supposed to be automated. I had installed iconv using vcpkg through the command line, but when I instead just opened the folder in Visual Studio, the CMake automatically started configuring. It still had an error at first, but opening VS as admin solved that, so it configured, generated, and then I was able to build it. 

I now have the executable opening, but starts up with this error:
`[ERROR]   - WIN_SERVICE: Failed to open handle to win service "NahimicService"..`

Is this service required?

**Comment by JoshuaMKW** [comment]
It is not. In fact, the whole purpose of detecting that service is to tell you to turn it off if you have it. Basically Nahimic with OpenGL is bugged and causes crashes when you resize the window.

Anyways, that message is a bit misleading but I haven't bothered fixing it because I'm working on more critical things.

**Comment by JoshuaMKW** [comment]
Hey,

You will want to open the extracted archive of a scene if you want to start messing with the program. This will be the scene folder you get after extracting the scene archive, not the scene folder that contains all scenes.

Eventually the structure of project handling will be changed, and certain branches of this program even have a beginning concept of a project directory (which is currently just the extracted ISO).

Hope this helps.
